### ISSUE TITLE
Raw data is annoyingly in an xls file

### ISSUE THREAD

**Issue by wcornwell** [daniel1noble/evolplasticty#1]
Write a function to read an excel file into R.  Annoyingly the `xlsx` package only works with the new excel files and isn't happy with the old ones.

**Comment by daniel1noble** [comment]
I know. I hate .xls, I don't normally use this, but thought I would provide some code to deal with it in case it is used by others. Script should all read fine and xls creates some problems, which is useful for showing processing. Can change though! I've written in data/output folder the .csv file, which I haven't added yet because I wanted to show ignore and how you don't want to ignore the data etc.

**Comment by daniel1noble** [comment]
Should be the gdata package. Tried last night and seemed to work...work on your end? I can just track the .csv data quick too.

**Comment by wcornwell** [comment]
works
